### ISSUE TITLE
Adding name with data

### ISSUE THREAD

**Issue by TheKlimoT** [scruffyboy13/Economy#6]
Hello!
please add row name.

name: TheKlimoT
UUID: UUID
balance: .....

Thank you! Or add migrate, i on MySQL storage, me need migrate all balance in database :)

**Comment by akrentz6** [comment]
Hi, since a username can change it's inefficient and unnecessary to add that to the database, why do you need it? if you need to find a player's balance you can either look at it through console or by going to a site like https://mcuuid.net/ and converting the username to a uuid there then looking at the database.

tldr: The database is meant for storing the balance not for looking at it so it doesn't have the player's username

**Comment by TheKlimoT** [comment]
my server using offline-mode.

**Comment by TheKlimoT** [comment]
How to migrate data in mysql?

**Comment by akrentz6** [comment]
what do you mean? migrate from mysql to what

**Comment by TheKlimoT** [comment]
Your initial storage goes to data, that is, in yml format, I moved to mysql format, but the balance of all players became 0, I mean that you should migrate from yml to mysql, if a different storage format is selected.

/economy migrate mysql/yml/h2/sqllite, depending on what format is available and installed. Please :)

**Comment by akrentz6** [comment]
I'm currently adding a way to migrate from yml to mysql but it won't be finished for a bit as i dont have much time right now
